### ISSUE TITLE
Filter out generated code by default

### ISSUE THREAD

**Issue by gavv** [gavv/returnstyles#1]
Adjust linter to detect generated files and ignore them by default.

The algorithm can be adopted from `exhaustive` linter: https://github.com/nishanths/exhaustive/blob/master/comment.go. We can replicate its isGeneratedFile() function and use it in run() to skip generated files.

Steps:

* in `run()`, pass `stack` to `skip()` function
* in `skip()`, get the very first stack frame and cast it to `ast.File`
* do a check similar to `isGeneratedFile` from `exhaustive` to determine if file is generated
* skip file if it is generated

We should also add new option `-include-generated` to disable this new behavior:

* to command-line options
* to YAML config
* to README

If this option is set, we should NOT skip generated files.

We should also add two new tests:

* with generated code, without `-include-generated` option; diagnostic should NOT be printed for generated code
* with generated code, with `-include-generated` option; diagnostic should BE printed for generated code

**Comment by nhAnik** [comment]
Hi @gavv , can I work on this?

**Comment by gavv** [comment]
@nhAnik Sure, thanks!
