### ISSUE TITLE
Add `-include-cgo` option and tests for cgo

### ISSUE THREAD

**Issue by gavv** [gavv/returnstyles#2]
Currently we unconditionally skip cgo functions:

```go
func skip(funcNode ast.Node) bool {
	switch funcNode := funcNode.(type) {
	case *ast.FuncDecl:
		if strings.HasPrefix(funcNode.Name.Name, "_Cfunc_") {
			return true
		}
	}
```

We should also add new option `-include-cgo` to disable this behavior:

* to command-line options
* to YAML config
* to README

If this option is set, we should NOT skip cgo functions.

We should also add two new tests:

* with cgo, without `-include-cgo` option; diagnostic should NOT be printed for cgo functions
* with cgo, with `-include-generated` option; diagnostic should BE printed for cgo functions

**Comment by OllieWillette667** [comment]
I will try to add this

**Comment by gavv** [comment]
Thanks!

**Comment by OllieWillette667** [comment]
![Untitled](https://github.com/gavv/returnstyles/assets/97988845/f09e91d7-5793-46e0-9245-3785804105f0)

@gavv do you have any idea why the testAnalyzer is failing for include_cgo?

**Comment by gavv** [comment]
You probably put "want" pragma on wrong line in your test. Or maybe you used dark sarcasm in the classroom, it's not allowed.

**Comment by gavv** [comment]
Dismissed.
